
export enum Currency {
  HKD = 'HKD',
  RMB = 'RMB',
  USD = 'USD'
}

export enum Entity {
  PROPERTY = '地产分部',
  ENTERPRISE = '集团总部'
}

export enum TransactionCategory {
  OPERATING = '经营活动',
  FINANCING = '筹资活动',
  INVESTING = '投资活动',
  INTERNAL = '内部调拨'
}

export enum TransactionStatus {
  ACTUAL = '实际发生',
  FORECAST = '计划预测'
}

export enum Benchmark {
  SHIBOR = 'SHIBOR', // RMB
  HIBOR = 'HIBOR',   // HKD
  SOFR = 'SOFR',     // USD
  LPR = 'LPR',       // Loan Prime Rate
  FIXED = 'FIXED'    // Fixed Rate
}

export enum LoanType {
  SYNDICATED = '银团贷款',
  BILATERAL = '双边贷款',
  BOND = '信用债券',
  NOTES = '中期票据'
}

export interface Transaction {
  id: string;
  date: string; // YYYY-MM-DD
  entity: Entity;
  category: TransactionCategory;
  description: string;
  amountHKD: number;
  amountRMB: number;
  amountUSD: number;
  status: TransactionStatus;
  linkedDebtId?: string; // To track if this was generated by a debt instrument
}

export interface Debt {
  id: string;
  name: string;             // e.g. "2024 地产分部 5年期银团贷款"
  bankName: string;         // Lead bank or counterparty
  loanType: LoanType;
  entity: Entity;
  currency: Currency;
  principal: number;        // In millions
  baseRate: number;         // Annual percentage, e.g. 4.5
  benchmark: Benchmark;
  spread: number;           // Basis points added to benchmark (for display/calc)
  startDate: string;
  endDate: string;
  frequency: 'MONTHLY' | 'QUARTERLY' | 'SEMI_ANNUALLY' | 'ANNUALLY' | 'AT_MATURITY';
  status: 'ACTIVE' | 'PLANNED' | 'SETTLED';
  guarantor?: string;       // e.g. "集团全额担保"
  remarks?: string;
}

export interface ExchangeRates {
  HKD_TO_RMB: number;
  USD_TO_RMB: number;
}

export interface MonthlySummary {
  month: string;
  totalInflow: number;
  totalOutflow: number;
  netFlow: number;
  endingBalance: number;
}